[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Nahin-Imtiaz/CSC448--Artificial-Intelligence/blob/master/Assignment_3/Assignment_3.ipynb)

In [1]:
# Imports section
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score
from sklearn import metrics
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import Pipeline

# Part 1. Loading the dataset

In [2]:
# Using pandas load the dataset (load remotely, not locally)
# Output the first 15 rows of the data
# Display a summary of the table information (number of datapoints, etc.)

df = pd.read_csv('https://raw.githubusercontent.com/profmcnich/example_notebook/main/science_data_large.csv')
df.head(15)

Temperature °C  Mols KCL     Size nm^3
0              469       647  6.244743e+05
1              403       694  5.779610e+05
2              302       975  6.196847e+05
3              779       916  1.460449e+06
4              901        18  4.325726e+04
5              545       637  7.124634e+05
6              660       519  7.006960e+05
7              143       869  2.718260e+05
8               89       461  8.919803e+04
9              294       776  4.770210e+05
10             991       117  2.441771e+05
11             307       781  5.006455e+05
12             206        70  3.145200e+04
13             437       599  5.390215e+05
14             566        75  9.185271e+04

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Temperature °C  1000 non-null   int64  
 1   Mols KCL        1000 non-null   int64  
 2   Size nm^3       1000 non-null   float64
dtypes: float64(1), int64(2)
memory usage: 23.6 KB


In [4]:
df.describe()

Temperature °C     Mols KCL     Size nm^3
count     1000.000000  1000.000000  1.000000e+03
mean       500.500000   471.530000  5.086111e+05
std        288.819436   288.482872  4.474838e+05
min          1.000000     1.000000  1.611429e+01
25%        250.750000   226.750000  1.298267e+05
50%        500.500000   459.500000  3.827182e+05
75%        750.250000   710.250000  7.603211e+05
max       1000.000000  1000.000000  1.972127e+06

# Part 2. Splitting the dataset

In [5]:
# Take the pandas dataset and split it into our features (X) and label (y)

# Use sklearn to split the features and labels into a training/test set. (90% train, 10% test)
df[['Size nm^3']] = df[['Size nm^3']].round(5)
X = df[['Temperature °C','Mols KCL']]
y = df['Size nm^3']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.10, random_state=42)

# Part 3. Perform a Linear Regression

In [6]:
# Use sklearn to train a model on the training set

# Create a sample datapoint and predict the output of that sample with the trained model

# Report on the score for that model, in your own words (markdown, not code) explain what the score means

# Extract the coefficents and intercept from the model and write an equation for your h(x) using LaTeX
Linear = LinearRegression().fit(X_train, y_train)

In [7]:
y_pred = Linear.predict(X_test)

In [8]:
print('The MSE is:',metrics.mean_squared_error(y_test, y_pred, squared=True))

The MSE is: 25153353484.244442


In [9]:
Linear.score(X_test,y_test)

0.8552472077275826

In [10]:
df = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
df

Actual     Predicted
521  1.177623e+05  2.359112e+05
737  8.687293e+05  8.304518e+05
740  1.084893e+06  9.694017e+05
660  1.716039e+06  1.326783e+06
411  9.536850e+05  8.849870e+05
..            ...           ...
436  6.305199e+05  7.039601e+05
764  7.676234e+05  8.520354e+05
88   8.684308e+05  8.891874e+05
63   9.737511e+05  9.366853e+05
826  4.786314e+03 -2.966941e+05

[100 rows x 2 columns]

###### The score of the model is 0.86 meaning that the model has 86 percent accuracy of predicting the size given the temperature and mol.

In [11]:
Linear.coef_

array([ 866.14641337, 1032.69506649])

In [12]:
Linear.intercept_

-409391.47958335094

###### $h(x) = -409391.48+866.15x_{1}+1032.7x_{2}$

# Part 4. Use Cross Validation

In [13]:
# Use the cross_val_score function to repeat your experiment across many shuffles of the data

# Report on their finding and their significance
LR = LinearRegression()
scores = cross_val_score(LR, X, y, cv=5)

In [14]:
scores

array([0.83918826, 0.87051239, 0.85871066, 0.87202623, 0.84364641])

In [15]:
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

0.86 accuracy with a standard deviation of 0.01


# Part 5. Using Polynomial Regression

In [16]:
# Using the PolynomialFeatures library perform another regression on an augmented dataset of degree 2

# Report on the metrics and output the resultant equation as you did in Part 3.
model = Pipeline([('poly', PolynomialFeatures(degree=2)), ('linear', LinearRegression(fit_intercept=False))])
model = model.fit(X_train, y_train)
model.score(X_test,y_test)

1.0

###### The score of the model is 1.00 meaning that the model has 100 percent accuracy of predicting the size given the temperature and mol.

In [17]:
model.named_steps['linear'].coef_.round(2)

array([ 0.  , 12.  , -0.  ,  0.  ,  2.  ,  0.03])

In [18]:
model.named_steps['linear'].intercept_

0.0

###### $h(x) = 0+0x_{1}+12x_{1}^2+0x_{1}^3+0x_{1}^4+2x_{1}^5+0.03x_{1}^6$